## Basic NumPy Functionality

### NumPy n-dim array
* Part of a Data "ecosystem" which includes data science libaries, machine learning and image processing
* NumPy is huge and very powerful --> we will just hit the highlights
* optimized array, superior to lists
* can be "any" number of dimensions, typically 1 or 2 dims though
* restricted to a single data type
* required to "dimension" your arrays when you initialize them 

In [1]:
import numpy as np

In [2]:
l = [1, 2, 3] 
a = np.array([1,2,3])

### Performance

In [4]:
big_arr = np.arange(4.5e6)
big_list = big_arr.tolist()

len(big_arr)

4500000

In [6]:
%timeit -n10 square = [x ** 2 for x in big_list]

549 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit -n10 square = big_arr ** 2

9.47 ms ± 3.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Determining dimensions
* size = "rows" * "columns"
* itemsize --> number of bytes used by a single value
* itemsize * size = bytes of memory the array uses
* shape --> comma separated tuple of length of each dimension
* ndim --> int value of dimensions present
* reshape --> dimension manipulation

In [9]:
arr = np.arange(15)
arr.size

15

In [10]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
print(arr.ndim)
print(arr.itemsize)

1
8


In [ ]:
arr.reshape(-1)

### "Slicing"

In [14]:
arr = arr.reshape(3,5)
arr[:,0]

array([ 0,  5, 10])

### Special arrays
* useful for dimensioning an array before you aknow what values it will hold

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(0)

array([], dtype=float64)

In [19]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Working with random numbers
* many different distribution options
* normal and uniform most common
* normal, standard_normal
* randn, randint

### Standard normal
* mean 0
* std 1
* takes a single optional argument --> n
* `np.random.standard_normal([size])`

In [20]:
import numpy.random as npr
npr.standard_normal(5)

array([-1.94213771,  0.95200493, -1.91173133,  0.95460752,  0.57006972])

### Uniform Distributions
* `np.random.randn(size=None)`
* `np.random.randint(low, high=None, size=None, dtype=int)`
    * excludes high --> called a half-open interval

In [21]:
npr.randn()

-0.750870539302426

In [22]:
npr.randint(1,7, size = 20)

array([1, 5, 3, 4, 3, 4, 1, 4, 1, 2, 4, 2, 6, 3, 3, 1, 5, 2, 2, 3])

### Normal
* loc = mean
* scale = std
* if not specified mean = 0, std = 1

In [23]:
x = npr.normal(size=50)

In [24]:
print(x.mean())
print(x.std())
print(x.max())
print(x.min())
# there is no median method

-0.0010438363080331936
0.9559958286314462
1.8287692235873918
-1.9110001324099828


In [25]:
np.percentile(x, [5, 50, 95])

array([-1.56326865,  0.05174018,  1.65114763])

### Simple Linear Modeling

In [26]:
import matplotlib.pyplot as plt

In [ ]:
x = npr.normal(size = 50)

### More syntactically intense method to do the same thing
* Requires a "dummy" variable next to actual x variable
* The rcond allows for special handling of extremely small values 

### Fill array with uniformly spaced data points between a minimum and maximum